#!/bin/bash
# Generate daily tasks based on active goals
# Runs every morning at 7:30 AM (before morning brief)

echo "=== Daily Task Generation ==="
echo "Date: $(date '+%Y-%m-%d %H:%M')"
echo ""

# Read active goals
echo "📋 Reading active goals..."
cat ~/.openclaw/workspace/memory/autonomous-tasks/goals/active-goals.md | grep -A 20 "Goal [0-9]:"

echo ""
echo "🤖 Generating tasks for today..."

# Create today's task file
TODAY=$(date '+%Y-%m-%d')
TASK_FILE="/Users/gwangmin/.openclaw/workspace/memory/autonomous-tasks/tasks/${TODAY}.md"

cat > "$TASK_FILE" << EOF
# 📅 Tasks for ${TODAY}

## Generated at $(date '+%H:%M')

### High Priority
- [ ] Continue building autonomous task system
- [ ] Test overnight task execution
- [ ] Update documentation

### Medium Priority
- [ ] Research additional OpenClaw use cases
- [ ] Plan next mini-app project

### Overnight Queue (Auto-execute)
- [ ] Fetch and summarize RSS news
- [ ] Check GitHub for updates
- [ ] Generate tomorrow's task preview

## Notes
Tasks generated by autonomous system.
EOF

echo "✅ Tasks saved to: ${TASK_FILE}"
